[DEBUG] 2022-07-31 14:08:24,713 - ファイルがある (Logging.py)
[DEBUG] 2022-07-31 14:13:08,168 - ファイルがある (Logging.py)
Traceback (most recent call last):
  File "C:\Users\user\Kani\python\sapu\TraceBack\code1.py", line 14, in main
    code2.func1()
  File "C:\Users\user\Kani\python\sapu\TraceBack\code2.py", line 2, in func1
    func2()
  File "C:\Users\user\Kani\python\sapu\TraceBack\code2.py", line 5, in func2
    result = 1/0
ZeroDivisionError: division by zero
